---
---
---

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(naniar)
library(forcats)
library(wordcloud)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(tidytext)
```

```{r}
library(tidyverse)
library(knitr)
library(openintro)
library(gridExtra)
```
```{r}
library(ggforce)
theme_set(theme_bw(16))
```

```{r}
library(zoom)
```

```{r}
library("tmap")
library("tmaptools")
library("sf")
library("leaflet")
```

```{r}
library("readxl")

chicago_crime = read.csv("chicago_crime.csv")
head(chicago_crime)
```

```{r}
ChicagoCrime <- chicago_crime %>% select(Date, Primary.Type, Arrest, 
                                           Domestic, District)
ChicagoCrime = ChicagoCrime %>% separate(Date,c("month", "data", "year"), sep = "/")

ChicagoCrime = ChicagoCrime %>% separate(year,c("year", "time"), sep = " ")
```

```{r}
ChicagoAssault <- ChicagoCrime %>% 
  filter(Primary.Type %in% c("ASSAULT"))

head(ChicagoAssault)
```

```{r}
ChicagoAHT <- ChicagoCrime %>%
  filter(Primary.Type %in% c("ASSAULT", "HOMICIDE", "THEFT"))

head(ChicagoAHT)
```

```{r}
ggplot(data = ChicagoAHT, mapping = aes(x = month, 
                                         fill = Primary.Type)) +
    geom_bar(position = "dodge") +
  ggtitle("Amount of Assault, Homicide, and Theft By Month") + 
  xlab("Month") + 
  ylab("# of Crimes") 
```

```{r}
library("readxl")

ChicagoAslt_Wth = read.csv("assault.csv")
head(ChicagoAslt_Wth)
```

```{r}
ggplot(data=ChicagoAslt_Wth, aes(x=Max.Temp)) + 
  geom_density(alpha=0.2, color= "lightblue", fill="lightblue") + 
  ggtitle("Frequency of Assault Crimes Based on Maximum Temperature") +
  xlab("Max Temp (C)") + 
  ylab("Frequency") 
```

```{r}
ggplot(data=ChicagoAslt_Wth, aes(x=Precipitation)) + 
  geom_density(alpha=.2, color="green", fill="green")+ 
  ggtitle("Frequency of Assault Crimes Based on Precipitation") +
  xlab("Accumulated Precipation (mm)") + 
  ylab("Frequency")
```


```{r}
ChicagoAslt_Wth$Precipitation1 <- as.factor(ifelse(ChicagoAslt_Wth$Precipitation > 2.7, 'yes', 'no'))
```

```{r}
ggplot(data=ChicagoAslt_Wth, aes(x=Precipitation1)) + 
  geom_bar(fill="lightgreen",color="lightgreen")  + 
  ggtitle("Amount of Assault Crimes when Precipation is Higher than Average") + 
  xlab("Precipation Higher Than Average") + 
  ylab("# of Assault Crimes") 
```
